### ISSUE TITLE
Consider renaming assemblies to follow Microsoft guidelines

### ISSUE THREAD

**Issue by tiesont** [mehdime/DbContextScope#14]
This is related to #2 

Microsoft's [naming guidelines](https://msdn.microsoft.com/en-us/library/ms229002) suggest using a format similar to

```
<Company>.<Component>.dll
```

when creating assemblies. The current structure of this project doesn't really work for that, as you've separated the interfaces and implementation into two projects. So, I would recommend a two step modification:

1. Combine the implementation and interface projects, as you're not really gaining anything by having them split, and
2. Renaming the project to something like Mehdime.Entity.

I can actually do both of these myself on a fork and submit a pull request, if you prefer. Once that is done, I can compile a single .dll for the NuGet package.

Obviously, this would be a breaking change for anyone using the existing code.

**Comment by maldworth** [comment]
:+1:  for a fork + pull request and a nuget package!

**Comment by tiesont** [comment]
@maldworth If you're interested in being a bit of a test subject, you can try the NuGet package I've uploaded here: https://drive.google.com/open?id=0By4iYTLNHcYRMVJ2SG9xSlMxVWM&authuser=0

Extract the 7zip archive. You'll have to create a [local NuGet source](http://docs.nuget.org/create/hosting-your-own-nuget-feeds#creating-local-feeds), and then you can add this package to a project. Everything was moved to a Mehdime.Entity namespace, but other than that no code changes, so it should just work.

**Comment by maldworth** [comment]
@tiesont I just tried it and the nupkg and it works great. I'm curious if the Interfaces should be either broken into a separate namespace, or a separate package. I like to separate my contracts from implementation. What is the standard nuget packaging guidelines for implementation and contract separation?

**Comment by tiesont** [comment]
@maldworth I don't recall that there are NuGet guidelines for namespaces. I can see separating the interfaces into a separate namespace, but what is gained by doing so? The current codebase actually does this, but also keeps them in separate assemblies. I didn't want to deploy them like that as a NuGet package, so I combined them.

I take the stance that assemblies like System.Web, et al, don't separate namespaces or assemblies at that level; you can organize classes and whatnot into folders within the solution & project, but namespaces don't need to reflect that.

**Comment by maldworth** [comment]
@tiesont Yeah, Nothing is gained in this scenario. I'm good with the package as you provided. Let me know when you upload it to Nuget.org!

**Comment by tiesont** [comment]
@maldworth Uploaded to https://www.nuget.org/packages/Mehdime.Entity/ - let me know if you have any issues with the "live" package.

**Comment by ChrisMarinos** [comment]
Can you submit a pull request for this work? It's pretty confusing that the nuget package doesn't match the repository.

**Comment by tiesont** [comment]
@ChrisMarinos I suppose I should. I'll see if I can get around to it at some point.

It's worth pointing out that @mehdime never gave a "yay/nay" response to this suggestion. I went ahead and published the NuGet package with *my* version mostly because it's what I had handy, and I don't like pushing multiple assemblies in one package if I can avoid it.

**Comment by ChrisMarinos** [comment]
Yeah, that makes sense. PR or not, it would just be good to have the code that you used to publish the package somewhere on github.

**Comment by tiesont** [comment]
@ChrisMarinos Pushed code to [my fork](https://github.com/tiesont/DbContextScope), and [pull request created](https://github.com/mehdime/DbContextScope/pull/19). We'll see what @mehdime says.

**Comment by mehdime** [comment]
Hi guys,

Pull request merged. And apologies for the silence in the last while - I'll try to address all open issues in the next week. I should have a little bit of free time then.

Thanks a lot!

**Comment by tiesont** [comment]
@mehdime Awesome. Did I ever ask if you have a NuGet account? I'd like to add you to the package as an owner. My contact info is public on my profile, if you can send me a quick email.

**Comment by mehdime** [comment]
Sent email.
