### ISSUE TITLE
No default Instance is registered and cannot be automatically determined for type

### ISSUE THREAD

**Issue by ershad65** [mehdime/DbContextScope#15]
I am using structure map for DI and i get below error while resolving. Do you know how should we configure it?
No default Instance is registered and cannot be automatically determined for type IDBContextFactory

**Comment by vaizeman** [comment]
I use something like this and seems to work:
For<IDbContextScopeFactory>().Use(new DbContextScopeFactory(null));

**Comment by ershad65** [comment]
Thanks vaizeman. I figured same. I use singleton as its a factory.
For<IDbContextScopeFactory>().Use(new DbContextScopeFactory()).Singleton();
