### ISSUE TITLE
NuGet package

### ISSUE THREAD

**Issue by sickboy** [mehdime/DbContextScope#2]
Loving this... how about a NuGet?

**Comment by tiesont** [comment]
@mehdime If you like, I can create and upload the initial package, and then transfer ownership to your account.

**Comment by LordDawnhunter** [comment]
+1

**Comment by mehdime** [comment]
Hi Guys. Thanks for all the comments and really sorry not having got back to you earlier. Work's been hectic and we just moved home so haven't had time to keep up with GitHub. 

I'll try and answer the outstanding open issues in the coming days.

@tiesont I've never published a nuget package before so I don't know yet what's involved. If you'd like to help, go for it! I'll try and get a nugget package up this week in any case.

**Comment by micdenny** [comment]
If you want I can also setup something with AppVeyor, to automatically build and publish to nuget.org.

I done this in 2 minutes (on my fork):

[![Build status](https://ci.appveyor.com/api/projects/status/w9pqu5ebgqrce5d4?svg=true)](https://ci.appveyor.com/project/micdenny/dbcontextscope)


Then we just need to figure out how to properly versioning and add `.nuspec` on the project to publish.

**Comment by sickboy** [comment]
Great news everyone, and welcome back mehdime!

**Comment by tiesont** [comment]
@mehdime Either works for me. @micdenny's suggestion obviously involves less manual intervention from you whenever you push updates to the repository. I just use the [Package Explorer](http://npe.codeplex.com/) to create and publish packages manually.

**Comment by LucasMetal** [comment]
+1

**Comment by tamirdresher** [comment]
+1

**Comment by Badmoonz** [comment]
+1

**Comment by tiesont** [comment]
@mehdime Since there seems to be at least a handful of people that want a NuGet package, I'll go ahead and create and publish one. If you can send me an email with your NuGet user name, I'll add you as a package owner.

**Comment by Garciat** [comment]
+1

**Comment by aoancea** [comment]
+1

**Comment by LiamBlizard** [comment]
+1

**Comment by vipasane** [comment]
+1. @tiesont Have you been able to publish already and if so where can we find this?

**Comment by rpmdejong** [comment]
+1

**Comment by tiesont** [comment]
@vipasane I've created a NuGet package, but I've been holding off on publishing it until I get some feedback on the linked issue (renaming the assemblies), since I'd prefer to drop a single .dll vs the two the current project structure requires. I could generate a zipped package if you want to give it a whirl.

**Comment by tiesont** [comment]
Okay, for those interested, Nuget package is uploaded to https://www.nuget.org/packages/Mehdime.Entity/

I went ahead with the changes proposed in #14 , so the namespaces do not reflect the code in the project at this point; the code itself was not changed.

**Comment by vipasane** [comment]
Just replaced dll depencies with nuget, works like a charm. Thank you @tiesont

**Comment by stokara** [comment]
Please update the nuget to contain signed dlls

**Comment by tiesont** [comment]
@stokara Unless and until I get some sort of feedback from mehdime on my changes, it's not worth the effort for me to do signed dlls. I can make you a package owner if you want to do the work yourself.

**Comment by cdemaskey** [comment]
AMAZING! Thanks for the nuget package!
