### ISSUE TITLE
Nuget Package?

### ISSUE THREAD

**Issue by StevenTCramer** [mehdime/DbContextScope#21]
Just wondering if you have thought about publishing this as a Nuget Package?

**Comment by ChrisMarinos** [comment]
https://www.nuget.org/packages/Mehdime.Entity/

Also see #2

**Comment by tiesont** [comment]
It might be worth adding 'DbContextScope' to the tags for the package, since I would assume that is what Steven searched on. <del>I'll try to update the package tonight.</del> <ins>Tag added. It will take a little while for the indexing on NuGet.org to update, but this should help.</ins>

**Comment by StevenTCramer** [comment]
Cool.  Yep! you are right I couldn't find it using DbContextScope.  It is easier to bring into a project as a nuget.  Thanks!

**Comment by StevenTCramer** [comment]
Yep found via DbContextScope Tag.
