### ISSUE TITLE
signing assembly

### ISSUE THREAD

**Issue by maldworth** [mehdime/DbContextScope#23]
Hey @tiesont and @mehdime, I'd like to sign the assembly because I'm prevented from using it in one of my projects because it's not strongly named. We obviously don't want to commit a private signature key to the repo. If you guys will sign the assembly then that's great otherwise can you give me access in Nuget and I can sign the latest one then Share the signing key among us (through email, dropbox, drive, or however we agree to share the key).

Thanks

**Comment by tiesont** [comment]
@mehdime is the project owner, so this is just my opinion, but I don't
think signing the assembly provides any real benefit.

You can always fork the repo and sign your own copy. Otherwise, I'd
recommend creating another package, with perhaps a similar name, like
Mehdime.Entity.Signed. That would allow anyone who wants to use the library
to decide if they want the signed version or not.

**Comment by maldworth** [comment]
@tiesont yeah, no reason to discuss the merits for signed or unsigned DLL of an open source project, but I like your idea for me to fork and then I'll create a Nuget.org project named _Mehdime.Entity.Signed_. I looked in your fork for a .Nuspec file that you used to make it but I couldn't find one. I can generate one from the proj but I would like to keep it consistent with the unsigned package you made. Could you gisthub it or send it to me perhaps? Thanks!

**Comment by tiesont** [comment]
@maldworth There currently isn't a .nuspec file, as I normally just use the Package Explorer to build the package manually. I'll see if I can find a few minutes to generate one and do a pull request.

**Comment by tiesont** [comment]
@maldworth This is the nuspec file the current package uses: https://gist.github.com/tiesont/8929a952be112f9cc7e3 - I don't think I'll have time to add one to the build process anytime soon, so that's the best I can do.

**Comment by maldworth** [comment]
great thanks @tiesont !
