### ISSUE TITLE
PCL & Xamarin

### ISSUE THREAD

**Issue by reader-man** [mehdime/DbContextScope#39]
Hi, 
Does this mean that the fork:
https://github.com/ninety7/DbContextScope

Will run on PCL and possible Xamarin when .Net core finalize?

I wanted to post this to:
https://github.com/ninety7/DbContextScope
but the issues tab is not visible/enabled.

**Comment by ninety7** [comment]
@reader-man In order to achieve .Net Core compatibility, there must be a way to avoid using Full .Net FW namespaces. Not working actively on it, though.

**Comment by reader-man** [comment]
This is moved to its repository:
https://github.com/ninety7/DbContextScope/issues/1
