### ISSUE TITLE
.net core

### ISSUE THREAD

**Issue by levalencia** [mehdime/DbContextScope#52]
Are you planning to rewerite this for .net core? I tried it myself but having issues with the main class.
http://mehdi.me/ambient-dbcontext-in-ef6/

http://stackoverflow.com/questions/43949175/where-is-dbcontexttransaction-con-net-core

**Comment by tiesont** [comment]
Might want to take a look at https://github.com/apawsey/DbContextScope - I haven't reviewed it, but if I go by the comments and commit messages, he seems to have a .NET Core compatible version.

**Comment by levalencia** [comment]
excellent!
